# Generated by Django 2.2.2 on 2019-06-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190623_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='c_journal_id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='c_article_id',
        ),
        migrations.RemoveField(
            model_name='references',
            name='c_article_id',
        ),
    ]
