# Generated by Django 2.2.2 on 2019-06-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190623_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('c_article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('doi', models.TextField(unique=True)),
                ('publication_date', models.TextField()),
                ('keyword', models.TextField()),
                ('c_journal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Journal')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('c_references_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('c_article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('c_author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('affiliate', models.TextField()),
                ('c_article_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Article')),
            ],
        ),
    ]
