# Generated by Django 2.2.2 on 2019-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_article_author_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.TextField(unique=True),
        ),
    ]
