# Generated by Django 2.2.2 on 2019-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190623_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_uri',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='uri',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issn',
            field=models.TextField(),
        ),
    ]
