# Generated by Django 2.2.2 on 2019-06-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190623_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='c_article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='c_author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='references',
            name='c_references_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
