# Generated by Django 2.2.2 on 2019-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190623_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_uri',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='uri',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='issue',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='volume',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
