# Generated by Django 2.2.2 on 2019-06-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190623_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='item_scraped',
            field=models.TextField(default='0'),
        ),
    ]
